# Generated by Codex on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="target_role",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
